// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/firebase_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: FirebaseConfig.webApiKey,
    appId: '1:97991498696:web:36d5010a4a742626d83efd',
    messagingSenderId: '97991498696',
    projectId: 'greencampus-949c7',
    authDomain: 'greencampus-949c7.firebaseapp.com',
    storageBucket: 'greencampus-949c7.firebasestorage.app',
    measurementId: 'G-N837RY5GRE',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: FirebaseConfig.androidApiKey,
    appId: '1:97991498696:android:79064442d1779af1d83efd',
    messagingSenderId: '97991498696',
    projectId: 'greencampus-949c7',
    storageBucket: 'greencampus-949c7.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: FirebaseConfig.iosApiKey,
    appId: '1:97991498696:ios:033a1b6ba23d3041d83efd',
    messagingSenderId: '97991498696',
    projectId: 'greencampus-949c7',
    storageBucket: 'greencampus-949c7.firebasestorage.app',
    iosBundleId: 'com.example.greenCampus',
  );
}
